# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# gem "rails"

gem 'sinatra'
gem 'activerecord'
gem 'sinatra-activerecord', :require => 'sinatra/activerecord'
gem 'rake'
gem 'require_all'
gem 'sqlite3'
gem 'shotgun'
gem 'pry'
gem 'bcrypt'
gem 'tux'
gem 'puma'

group :test do
  gem 'rspec'
  gem 'capybara'
  gem 'rack-test'
end